name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@4

      - name: Node installieren
        uses: actions/setup-node@4
        with:
          node-version: '20'

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: Playwright-Browser installieren
        run: npx playwright install --with-deps

      - name: Tests ausführen
        run: npx playwright test
